version: '3.8'

services:
    web:
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "8085:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            ppdbnet:

    db:
        image: mysql:latest
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8001:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            ppdbnet:
    phpmyadmin:
        image: phpmyadmin:latest
        networks:
            ppdbnet:
        ports:
            - "8002:80"
volumes:
    dbdata:

networks:
    ppdbnet:
