name: Deploy Laravel Project on push
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@master
      - name: Create production .env file
        run: |
          cat > .env << 'EOL'
          APP_NAME="SPMB SMP DISDIKPORA Cianjur 2025"
          APP_ENV=production
          APP_KEY=
          APP_DEBUG=false
          APP_URL=https://spmb.disdikpora-cianjur.com
          SITE_URL=https://spmb.disdikpora-cianjur.com
          SESSION_DOMAIN=.disdikpora-cianjur.com
          APP_URL_SCHEME=https
          APP_SSL=true
          FORCE_HTTPS=true

          LOG_CHANNEL=stack
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=error

          DB_CONNECTION=mysql
          DB_HOST=127.0.0.1
          DB_PORT=3306
          DB_DATABASE=spmbsmpdisdikporacianjur
          DB_USERNAME=spmbsmpdisdikporacianjur
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          RECAPTCHA_SITEKEY=6Lc7M_sqAAAAACO25jV6EMyt7R2TR4WH9W8u8xZ1
          RECAPTCHA_SECRET=6Lc7M_sqAAAAAIwV1A-ocISOiez_JIuOI6fy6f9D

          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          FILESYSTEM_DISK=local
          QUEUE_CONNECTION=database
          SESSION_DRIVER=file
          SESSION_LIFETIME=120

          MEMCACHED_HOST=127.0.0.1

          REDIS_HOST=127.0.0.1
          REDIS_PASSWORD=null
          REDIS_PORT=6379

          MAIL_MAILER=smtp
          MAIL_HOST=mailpit
          MAIL_PORT=1025
          MAIL_USERNAME=null
          MAIL_PASSWORD=null
          MAIL_ENCRYPTION=null
          MAIL_FROM_ADDRESS="hello@example.com"
          MAIL_FROM_NAME="${APP_NAME}"

          AWS_ACCESS_KEY_ID=
          AWS_SECRET_ACCESS_KEY=
          AWS_DEFAULT_REGION=us-east-1
          AWS_BUCKET=
          AWS_USE_PATH_STYLE_ENDPOINT=false

          PUSHER_APP_ID=
          PUSHER_APP_KEY=
          PUSHER_APP_SECRET=
          PUSHER_HOST=
          PUSHER_PORT=443
          PUSHER_SCHEME=https
          PUSHER_APP_CLUSTER=mt1

          VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
          VITE_PUSHER_HOST="${PUSHER_HOST}"
          VITE_PUSHER_PORT="${PUSHER_PORT}"
          VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
          VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

          VERSION="8.1.4"
          EOL
      - name: Create cache directories first
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/testing
          chmod -R 777 storage bootstrap/cache
      - name: Remove dev packages from composer.json
        run: |
          if [ -f "composer.json" ]; then
            sed -i 's/"barryvdh\/laravel-debugbar".*//g' composer.json
            sed -i 's/"barryvdh\/laravel-ide-helper".*//g' composer.json
          fi
      - name: Install Dependencies
        run: composer install --optimize-autoloader --no-dev --no-scripts
      - name: Generate key
        run: php artisan key:generate
      - name: Generate storage link
        run: php artisan storage:link
      - name: Run post-install scripts manually
        run: |
          composer dump-autoload
          php -d memory_limit=-1 artisan package:discover
      - name: Clear and optimize
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear
          php artisan optimize
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
